"""Generate the ros2_control description of JX1 from simulation/joint_map.yaml and rl/config/jx1_walk.yaml.

Writes
  ros2_ws/src/jx1_description/urdf/jx1.ros2_control.xacro   macro jx1_ros2_control(hardware): mock | topic
  ros2_ws/src/jx1_description/urdf/jx1_system.urdf.xacro    robot = generated jx1.urdf.xacro + ros2_control block
  ros2_ws/src/jx1_bringup/config/controllers.yaml           joint_state_broadcaster + forward position controller
Joint order everywhere = policy joints then held joints (the order of the jx1_policy node's command vector).
hardware:=topic uses topic_based_ros2_control/TopicBasedSystem on /jx1/joint_command + /jx1/joint_states, which the
MuJoCo node (jx1_sim) and Isaac Sim's ROS 2 bridge both speak; hardware:=mock uses mock_components/GenericSystem.
Usage: .venv/Scripts/python tools/sim/gen_ros2_control.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
URDF_DIR = ROOT / "ros2_ws" / "src" / "jx1_description" / "urdf"
BRINGUP = ROOT / "ros2_ws" / "src" / "jx1_bringup" / "config"


def joint_order():
    jm = yaml.safe_load((ROOT / "simulation" / "joint_map.yaml").read_text(encoding="utf-8"))
    rl = yaml.safe_load((ROOT / "rl" / "config" / "jx1_walk.yaml").read_text(encoding="utf-8"))
    all_joints = [j["name"] for j in jm["joints"]]
    policy = list(rl["policy_joints"])
    return policy + [j for j in all_joints if j not in policy], rl["default_joint_pos"], {j["name"]: j for j in jm["joints"]}


def main():
    order, default, jmap = joint_order()
    lines = ['<?xml version="1.0"?>',
             '<!-- Generated by tools/sim/gen_ros2_control.py from simulation/joint_map.yaml + rl/config/jx1_walk.yaml. Do not edit. -->',
             '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">',
             '  <xacro:macro name="jx1_ros2_control" params="hardware:=topic">',
             '    <ros2_control name="JX1System" type="system">',
             '      <hardware>',
             "        <xacro:if value=\"${hardware == 'mock'}\">",
             '          <plugin>mock_components/GenericSystem</plugin>',
             '          <param name="calculate_dynamics">true</param>',
             '        </xacro:if>',
             "        <xacro:if value=\"${hardware == 'topic'}\">",
             '          <plugin>topic_based_ros2_control/TopicBasedSystem</plugin>',
             '          <param name="joint_commands_topic">/jx1/joint_command</param>',
             '          <param name="joint_states_topic">/jx1/joint_states</param>',
             '          <param name="sum_wrapped_joint_states">false</param>',
             '        </xacro:if>',
             '      </hardware>']
    for j in order:
        lo, hi = jmap[j]["lower_rad"], jmap[j]["upper_rad"]
        lines += [f'      <joint name="{j}">',
                  f'        <command_interface name="position"><param name="min">{lo}</param><param name="max">{hi}</param></command_interface>',
                  f'        <state_interface name="position"><param name="initial_value">{default.get(j, 0.0)}</param></state_interface>',
                  '        <state_interface name="velocity"/>',
                  '        <state_interface name="effort"/>',
                  '      </joint>']
    lines += ['    </ros2_control>', '  </xacro:macro>', '</robot>', '']
    (URDF_DIR / "jx1.ros2_control.xacro").write_text("\n".join(lines), encoding="utf-8")
    system = ['<?xml version="1.0"?>',
              '<!-- JX1 + ros2_control. Generated by tools/sim/gen_ros2_control.py. xacro jx1_system.urdf.xacro hardware:=topic|mock -->',
              '<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="jx1">',
              '  <xacro:arg name="hardware" default="topic"/>',
              '  <xacro:include filename="$(find jx1_description)/urdf/jx1.urdf.xacro"/>',
              '  <xacro:include filename="$(find jx1_description)/urdf/jx1.ros2_control.xacro"/>',
              '  <xacro:jx1_ros2_control hardware="$(arg hardware)"/>',
              '</robot>', '']
    (URDF_DIR / "jx1_system.urdf.xacro").write_text("\n".join(system), encoding="utf-8")
    BRINGUP.mkdir(parents=True, exist_ok=True)
    ctrl = {"controller_manager": {"ros__parameters": {
                "update_rate": 200,
                "joint_state_broadcaster": {"type": "joint_state_broadcaster/JointStateBroadcaster"},
                "jx1_position_controller": {"type": "forward_command_controller/ForwardCommandController"}}},
            "jx1_position_controller": {"ros__parameters": {"joints": order, "interface_name": "position"}}}
    (BRINGUP / "controllers.yaml").write_text("# Generated by tools/sim/gen_ros2_control.py (joint order = jx1_policy command order)\n"
                                              + yaml.safe_dump(ctrl, sort_keys=False), encoding="utf-8")
    print(f"ros2_control: {len(order)} joints -> {URDF_DIR / 'jx1.ros2_control.xacro'}, jx1_system.urdf.xacro, {BRINGUP / 'controllers.yaml'}")


if __name__ == "__main__":
    main()
