"""Import the JX1 URDF into Isaac Sim, apply the per-joint drive gains and save USD.

Run with Isaac Sim's python.sh (UNVERIFIED here — no Isaac Sim on the design machine). Gains and effort limits come from
import_config.yaml, generated by tools/sim/build_robot_description.py from the same table as the MuJoCo model.
"""
import math
from pathlib import Path

import yaml
from isaacsim import SimulationApp

app = SimulationApp({"headless": True})
import omni.kit.commands  # noqa: E402
import omni.usd  # noqa: E402
from pxr import UsdPhysics  # noqa: E402

here = Path(__file__).resolve().parent
cfg_file = yaml.safe_load((here / "import_config.yaml").read_text(encoding="utf-8"))
urdf = (here / cfg_file["urdf"]).resolve()
ok, cfg = omni.kit.commands.execute("URDFCreateImportConfig")
cfg.merge_fixed_joints = cfg_file["merge_fixed_joints"]
cfg.fix_base = cfg_file["fix_base"]
cfg.import_inertia_tensor = cfg_file["import_inertia_tensor"]
cfg.self_collision = cfg_file["self_collision"]
cfg.convex_decomp = cfg_file["convex_decomposition"]
dest = str(here / cfg_file["output_usd"])
omni.kit.commands.execute("URDFParseAndImportFile", urdf_path=str(urdf), import_config=cfg, dest_path=dest)
stage = omni.usd.get_context().get_stage()
omni.usd.get_context().open_stage(dest)
stage = omni.usd.get_context().get_stage()
applied = 0
for prim in stage.Traverse():
    g = cfg_file["drive_gains"].get(prim.GetName())
    if g is None or not prim.IsA(UsdPhysics.RevoluteJoint):
        continue
    drive = UsdPhysics.DriveAPI.Apply(prim, "angular")
    drive.CreateTypeAttr("force")
    drive.CreateStiffnessAttr(g["kp_Nm_per_rad"] * math.pi / 180.0)     # PhysX: per degree
    drive.CreateDampingAttr(g["kd_Nms_per_rad"] * math.pi / 180.0)
    drive.CreateMaxForceAttr(g["max_effort_Nm"])
    applied += 1
stage.GetRootLayer().Save()
print(f"imported {urdf.name} -> {dest}; drive gains applied to {applied} joints")
app.close()
