// Generated by tools/gen_firmware_config.py — do not edit by hand.
#pragma once
#include "robstride.h"
#define HUB_ID 1
static const uint8_t HOST_CAN_ID = 0xFD;
static const uint32_t BUS_PERIOD_US = 2000;   // 500 Hz
static const uint32_t HOST_TIMEOUT_US = 50000; // -> damping
static const uint32_t CAN_TIMEOUT_US = 20000;  // stale feedback flag
static const uint8_t STATE_DIV = 2;            // state to host at 250 Hz
static const float SOFT_MARGIN = 0.0349f;     // 2 deg
static const float DAMPING_KD = 2.0f;
static const float TEMP_DERATE_C = 100.0f, TEMP_STOP_C = 130.0f;
static const int ESTOP_PIN = 2;
struct JointCfg { const char *name; uint8_t bus; uint8_t can_id; robstride::Model model; float sign; float zero; float q_min; float q_max; float tau_limit; };
static const int NJ = 10;
static const JointCfg JOINTS[NJ] = {
  {"right_hip_yaw", 0, 41, robstride::RS06, -1.0f, 0.0f, -0.78540f, 0.69813f, 28.8f},
  {"right_hip_roll", 0, 42, robstride::RS03, 1.0f, 0.0f, -0.78540f, 0.43633f, 48.0f},
  {"right_hip_pitch", 0, 43, robstride::RS04, -1.0f, 0.0f, -2.00713f, 0.61086f, 96.0f},
  {"right_knee", 1, 44, robstride::RS04, 1.0f, 0.0f, 0.00000f, 2.09440f, 96.0f},
  {"right_ankle_motorA", 1, 45, robstride::RS06, -1.0f, 0.0f, -1.30900f, 1.30900f, 28.8f},
  {"right_ankle_motorB", 1, 46, robstride::RS06, 1.0f, 0.0f, -1.30900f, 1.30900f, 28.8f},
  {"right_shoulder_pitch", 2, 51, robstride::RS02, -1.0f, 0.0f, -2.96706f, 1.04720f, 13.6f},
  {"right_shoulder_roll", 2, 52, robstride::RS02, 1.0f, 0.0f, -2.61799f, 0.17453f, 13.6f},
  {"right_shoulder_yaw", 2, 53, robstride::RS00, -1.0f, 0.0f, -1.57080f, 1.57080f, 11.2f},
  {"right_elbow", 2, 54, robstride::RS00, -1.0f, 0.0f, -2.35619f, 0.08727f, 11.2f},
};
