// Generated by tools/gen_firmware_config.py — do not edit by hand.
#pragma once
#include "robstride.h"
#define HUB_ID 0
static const uint8_t HOST_CAN_ID = 0xFD;
static const uint32_t BUS_PERIOD_US = 2000;   // 500 Hz
static const uint32_t HOST_TIMEOUT_US = 50000; // -> damping
static const uint32_t CAN_TIMEOUT_US = 20000;  // stale feedback flag
static const uint8_t STATE_DIV = 2;            // state to host at 250 Hz
static const float SOFT_MARGIN = 0.0349f;     // 2 deg
static const float DAMPING_KD = 2.0f;
static const float TEMP_DERATE_C = 100.0f, TEMP_STOP_C = 130.0f;
static const int ESTOP_PIN = 2;
struct JointCfg { const char *name; uint8_t bus; uint8_t can_id; robstride::Model model; float sign; float zero; float q_min; float q_max; float tau_limit; };
static const int NJ = 11;
static const JointCfg JOINTS[NJ] = {
  {"left_hip_yaw", 0, 11, robstride::RS06, -1.0f, 0.0f, -0.69813f, 0.78540f, 28.8f},
  {"left_hip_roll", 0, 12, robstride::RS03, 1.0f, 0.0f, -0.43633f, 0.78540f, 48.0f},
  {"left_hip_pitch", 0, 13, robstride::RS04, 1.0f, 0.0f, -2.00713f, 0.61086f, 96.0f},
  {"left_knee", 1, 14, robstride::RS04, -1.0f, 0.0f, 0.00000f, 2.09440f, 96.0f},
  {"left_ankle_motorA", 1, 15, robstride::RS06, 1.0f, 0.0f, -1.30900f, 1.30900f, 28.8f},
  {"left_ankle_motorB", 1, 16, robstride::RS06, -1.0f, 0.0f, -1.30900f, 1.30900f, 28.8f},
  {"left_shoulder_pitch", 2, 21, robstride::RS02, 1.0f, 0.0f, -2.96706f, 1.04720f, 13.6f},
  {"left_shoulder_roll", 2, 22, robstride::RS02, 1.0f, 0.0f, -0.17453f, 2.61799f, 13.6f},
  {"left_shoulder_yaw", 2, 23, robstride::RS00, -1.0f, 0.0f, -1.57080f, 1.57080f, 11.2f},
  {"left_elbow", 2, 24, robstride::RS00, 1.0f, 0.0f, -2.35619f, 0.08727f, 11.2f},
  {"waist_yaw", 2, 31, robstride::RS06, 1.0f, 0.0f, -1.57080f, 1.57080f, 28.8f},
};
