"""Generate docs/final_robot_specification.md — the FINAL ROBOT SPECIFICATION — from the evidence files.

Every number is read from a result file (never typed by hand): design point, joint map, CAD mass properties, actuator
catalogue, latest requirements, structural FEA summary, CAD/MuJoCo verification results and the BOM.
Usage: .venv/Scripts/python tools/gen_final_spec.py
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def load_json(rel):
    p = ROOT / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def load_yaml(rel):
    p = ROOT / rel
    return yaml.safe_load(p.read_text(encoding="utf-8")) if p.exists() else None


def v(x):
    return x["value"] if isinstance(x, dict) and "value" in x else x


def latest_requirements():
    for tag in ("iter2_C_cad_masses", "iter1_B_knee_and_pitch_RS04"):
        r = load_yaml(f"calculations/results/{tag}/requirements.yaml")
        if r:
            return tag, r
    return None, None


def main():
    dp = load_yaml("calculations/design_point.yaml")
    jm = load_yaml("simulation/joint_map.yaml")
    mp = load_json("simulation/mass_properties.json")
    cat = load_yaml("actuators/actuator_catalog.yaml")["classes"]
    tag, req = latest_requirements()
    st = load_json("calculations/results/structural/summary.json")
    pw = load_json("calculations/results/iter1_B_knee_and_pitch_RS04/power_budget.json")
    g = dp["geometry"]
    ub = dp["upper_body_geometry"]
    leg_len = v(g["thigh_m"]) + v(g["shin_m"]) + v(g["sole_to_ankle_m"])
    head_top = leg_len + v(ub["waist_yaw_origin"])[2] + v(ub["neck_yaw_origin"])[2] + v(ub["neck_pitch_offset"])[2] + v(ub["head_top_above_neck_pitch_m"])
    L = ["# JX1 — FINAL ROBOT SPECIFICATION", "",
         f"Generated by `tools/gen_final_spec.py` from the evidence files (design point v{dp['meta']['version']}). "
         "Labels: VERIFIED / MEASURED / CALCULATED / ESTIMATED / ASSUMED / UNVERIFIED. Nothing has been built or physically tested.", "",
         "```text", "JX1 FINAL ROBOT SPECIFICATION"]
    mass = mp["total_mass_kg"] if mp else None
    upper_src = "CAD" if mp and mp.get("upper_body") == "CAD" else "placeholder"
    L += [f"Height (zero pose, CAD)        : {head_top:.3f} m  [CALCULATED]",
          f"Mass (CAD, all components)     : {mass:.2f} kg  [ESTIMATED: CAD volumes x documented densities, datasheet actuator masses; upper body {upper_src}]" if mass else "Mass: n/a",
          f"Degrees of freedom             : {jm['dof']['total_actuated']} (legs {jm['dof']['legs']}, waist {jm['dof']['waist']}, arms {jm['dof']['arms']}, neck {jm['dof']['neck']})",
          f"Leg                            : thigh {v(g['thigh_m'])} m, shin {v(g['shin_m'])} m, ankle-sole {v(g['sole_to_ankle_m'])} m, hip spacing {v(g['hip_spacing_m'])} m",
          f"Foot                           : {v(g['foot']['length_m'])} x {v(g['foot']['width_m'])} m",
          "Leg kinematics                 : hip yaw-roll-pitch (intersecting), knee pitch, 2-motor parallel ankle (pitch/roll)"]
    L.append("")
    L.append("Actuators (joint: model, peak / rated torque, requirement peak)")
    cls_of = {"hip_yaw": "M", "hip_roll": "L", "hip_pitch": "XL", "knee": "XL", "ankle_motor": "M"}
    for j, c in cls_of.items():
        a = cat[c]
        r = req["leg_joint_requirements"].get(j, {}) if req else {}
        need = r.get("REQ_peak_torque_Nm")
        cap = v(a["peak_torque_Nm"])
        margin = f"{(cap / need - 1) * 100:+.0f} %" if need else "n/a"
        L.append(f"  {j:14s}: {a['product']:15s} {cap:>5} / {v(a['rated_torque_Nm']):>4} N m   need {need} N m ({margin})")
    L.append("  waist          : RobStride RS06     36 / 11 N m")
    L.append("  shoulder p/r   : RobStride RS02     17 / 6 N m ; shoulder yaw, elbow: RobStride RS00 14 / 5 N m ; neck: Waveshare ST3215 x2")
    L.append(f"  requirement source: calculations/results/{tag}/requirements.yaml (policy: peak = max(1.5 x dynamic, 1.25 x static))")
    L.append("")
    L.append("Structure (FEA: actuator-capped GRF samples + walking fatigue; SF LC1 / LC2, required 1.5 / 1.5 for aluminium)")
    if st:
        for key, r in st["parts"].items():
            m = r["materials"][r["recommended"]]
            L.append(f"  {r['stl']:22s}: {r['recommended']:8s} SF {m['SF_LC1']:5.2f} / {m['SF_LC2']:5.2f}  {'PASS' if m['pass'] else 'FAIL'}")
    L.append("")
    L.append("Compute / electronics : Jetson Nano 4 GB (policy 50 Hz) + 2 x Teensy 4.1 CAN hubs (6 x CAN 1 Mbit/s, 500 Hz), BNO085 IMU,")
    L.append("                        IMX219-83 stereo camera, RobStride on-board FOC drivers")
    if pw:
        sc = pw["scenarios"]
        pack = next((pk for k, pk in pw["packs"].items() if k.startswith("13S2P Samsung 50S")), {})
        L.append(f"Power                 : 13S2P Samsung 50S (41.6-54.6 V, {pack.get('energy_Wh', 468)} Wh); standing {sc['stand_idle']['mean_W']} W, "
                 f"walking {sc['walk_nominal_0.52ms']['mean_W']} W (0.52 m/s), {sc['walk_fast_0.79ms']['mean_W']} W mean / "
                 f"{sc['walk_fast_0.79ms']['peak_W']} W peak (0.79 m/s); runtime {pack.get('runtime_walk_nominal_h', '?')} h walking, "
                 f"{pack.get('runtime_standing_h', '?')} h standing  [CALCULATED, lower-body dynamics]")
    else:
        L.append("Power                 : 13S2P Samsung 50S (41.6-54.6 V, 468 Wh)")
    L.append("Safety                : dual-path E-stop (motor-bus switch + hub damping), 58 V branch fuses, smart BMS, host/CAN watchdogs")
    # verification
    ver = []
    for f, name in (("verification/leg_motion_verification_L.json", "left leg"), ("verification/leg_motion_verification_R.json", "right leg"),
                    ("verification/upper_motion_verification.json", "upper body"), ("verification/robot_motion_verification.json", "whole robot")):
        d = load_json(f)
        if d:
            ver.append(f"{name} {sum(r['kinematics_pass'] for r in d)}/{len(d)} kinematic, {sum(r['collision_free'] for r in d)}/{len(d)} collision-free")
    L.append("CAD verification      : " + "; ".join(ver))
    aw = load_json("verification/ankle_workspace_L.json")
    if aw:
        L.append(f"Ankle workspace       : {aw['collision_free_fraction'] * 100:.0f} % of the pitch x roll box collision-free; coupled limit polygon in joint_map.yaml")
    mj = load_json("verification/mujoco_validation.json")
    if mj:
        s_ = mj.get("standing", {})
        L.append(f"MuJoCo                : standing {'held' if not s_.get('fell') else 'FELL'} (max tilt {s_.get('max_tilt_deg')} deg), "
                 f"squat {'ok' if not mj.get('squat', {}).get('fell') else 'fell'}")
    # cost
    rows = list(csv.DictReader(open(ROOT / "bom" / "master_bom.csv", encoding="utf-8")))
    total = sum(float(r["Total INR"]) for r in rows if r["Status"] != "DEFERRED")
    act = sum(float(r["Total INR"]) for r in rows if r["Part"] == "Joint actuator")
    L.append(f"Cost (India, landed)  : Rs {total:,.0f} (+15 % contingency = Rs {total * 1.15:,.0f}); actuators {act / total * 100:.0f} %  [ESTIMATED/VERIFIED mix, bom/master_bom.csv]")
    L += ["```", "",
          "Details: [README](../README.md) · [architecture](architecture.md) · [structural report](../calculations/results/structural/report.md) · "
          "[open issues](open_issues.md) · [risk register](risk_register.md) · [BOM](../bom/cost_summary.md)", ""]
    (ROOT / "docs" / "final_robot_specification.md").write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))


if __name__ == "__main__":
    main()
