"""Generate firmware/hub/jx1_hub/config.h from the kinematic contract and the CAD mounting orientations.

Motor sign = +1 when the actuator's +Z (output) axis points along the robot joint axis in the zero pose
(same rule the verified SolidWorks assembly uses for its limit mates); limits from simulation/joint_map.yaml.
Ankle motors are driven in motor space (crank angle phi about the shin +Y axis); the host converts ankle
pitch/roll <-> phi with calculations/jx1calc/ankle.py.
Usage: .venv/Scripts/python tools/gen_firmware_config.py
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from cad.leg_kinematics import LegCAD  # noqa: E402

JM = {j["name"]: j for j in yaml.safe_load((ROOT / "simulation/joint_map.yaml").read_text(encoding="utf-8"))["joints"]}
MODEL = {"XL": "RS04", "L": "RS03", "M": "RS06", "S": "RS02", "XS": "RS00"}
PEAK = {"RS04": 120.0, "RS03": 60.0, "RS06": 36.0, "RS02": 17.0, "RS00": 14.0}
AXIS = {"hip_yaw": (0, 0, 1), "hip_roll": (1, 0, 0), "hip_pitch": (0, 1, 0), "knee": (0, 1, 0), "ankle_motorA": (0, 1, 0), "ankle_motorB": (0, 1, 0)}
HOUSING = {"hip_yaw": "YawH", "hip_roll": "RollH", "hip_pitch": "PitchH", "knee": "KneeH", "ankle_motorA": "AnkAH", "ankle_motorB": "AnkBH"}
CLASS = {"hip_yaw": "M", "hip_roll": "L", "hip_pitch": "XL", "knee": "XL", "ankle_motorA": "M", "ankle_motorB": "M"}


def leg_rows(side, base_id, hub_bus0):
    s = 1 if side == "left" else -1
    zero = LegCAD(s).component_poses({})
    rows = []
    for k, j in enumerate(["hip_yaw", "hip_roll", "hip_pitch", "knee", "ankle_motorA", "ankle_motorB"]):
        hz = zero[HOUSING[j]][:3, 2]
        sign = 1 if float(np.dot(hz, AXIS[j])) > 0 else -1
        if j.startswith("ankle"):
            lo, hi = math.radians(-75), math.radians(75)
        else:
            jm = JM[f"{side}_{j}_joint"]
            lo, hi = jm["lower_rad"], jm["upper_rad"]
        model = MODEL[CLASS[j]]
        rows.append((f"{side}_{j}", hub_bus0 + (0 if k < 3 else 1), base_id + k + 1, model, sign, lo, hi, 0.8 * PEAK[model]))
    return rows


def upper_sign(joint):
    """+1 when the actuator +Z (output) axis points along the robot joint axis in the zero pose (tools/cad/upper_kinematics)."""
    from cad.upper_kinematics import UpperCAD, ACTUATED
    uc = UpperCAD()
    poses, W0 = uc.component_poses({}), uc.links({})
    for j, hk, ok, axis in ACTUATED:
        if j == joint:
            ax = W0[uc.comps[hk][1]][:3, :3] @ np.array(axis, float)
            return 1 if float(np.dot(poses[hk][:3, 2], ax)) > 0 else -1
    raise KeyError(joint)


def arm_rows(side, base_id, bus):
    rows = []
    for k, (j, cls) in enumerate([("shoulder_pitch", "S"), ("shoulder_roll", "S"), ("shoulder_yaw", "XS"), ("elbow", "XS")]):
        jm = JM[f"{side}_{j}_joint"]
        model = MODEL[cls]
        rows.append((f"{side}_{j}", bus, base_id + k + 1, model, upper_sign(f"{side}_{j}"), jm["lower_rad"], jm["upper_rad"], 0.8 * PEAK[model]))
    return rows


def emit(rows, hub):
    lines = ["// Generated by tools/gen_firmware_config.py — do not edit by hand.", "#pragma once", "#include \"robstride.h\"",
             f"#define HUB_ID {hub}", "static const uint8_t HOST_CAN_ID = 0xFD;", "static const uint32_t BUS_PERIOD_US = 2000;   // 500 Hz",
             "static const uint32_t HOST_TIMEOUT_US = 50000; // -> damping", "static const uint32_t CAN_TIMEOUT_US = 20000;  // stale feedback flag",
             "static const uint8_t STATE_DIV = 2;            // state to host at 250 Hz", "static const float SOFT_MARGIN = 0.0349f;     // 2 deg",
             "static const float DAMPING_KD = 2.0f;", "static const float TEMP_DERATE_C = 100.0f, TEMP_STOP_C = 130.0f;",
             "static const int ESTOP_PIN = 2;",
             "struct JointCfg { const char *name; uint8_t bus; uint8_t can_id; robstride::Model model; float sign; float zero; float q_min; float q_max; float tau_limit; };",
             f"static const int NJ = {len(rows)};", "static const JointCfg JOINTS[NJ] = {"]
    for (n, bus, cid, model, sign, lo, hi, tl) in rows:
        lines.append(f'  {{"{n}", {bus}, {cid}, robstride::{model}, {sign:.1f}f, 0.0f, {lo:.5f}f, {hi:.5f}f, {tl:.1f}f}},')
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    hub_a = leg_rows("left", 10, 0) + arm_rows("left", 20, 2) + [("waist_yaw", 2, 31, "RS06", upper_sign("waist_yaw"), JM["waist_yaw_joint"]["lower_rad"], JM["waist_yaw_joint"]["upper_rad"], 28.8)]
    hub_b = leg_rows("right", 40, 0) + arm_rows("right", 50, 2)
    out = ROOT / "firmware/hub/jx1_hub"
    (out / "config_hub_a.h").write_text(emit(hub_a, 0), encoding="utf-8")
    (out / "config_hub_b.h").write_text(emit(hub_b, 1), encoding="utf-8")
    (out / "config.h").write_text("// Select the hub build: define JX1_HUB_B for hub B.\n#pragma once\n#ifdef JX1_HUB_B\n#include \"config_hub_b.h\"\n#else\n#include \"config_hub_a.h\"\n#endif\n", encoding="utf-8")
    for r in hub_a + hub_b:
        print(r[0], "bus", r[1], "id", r[2], r[3], "sign", r[4])


if __name__ == "__main__":
    main()
